[project]
name = "apache-airflow-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=2.10.5",
    "mlflow>=2.21.3",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
